//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SalesManagerApp.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SalesManagerApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   商品情報の読み込みに失敗しました。
        ///ファイル[product.csv]が見つかりません。
        ///以下の場所にファイルが保存されているか確認してください。
        ///{Path} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_001 {
            get {
                return ResourceManager.GetString("MSG-001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品情報の読み込みに失敗しました。
        ///ファイル[product.csv]が破損しています。
        ///ファイルの内容が正しいか確認してください。
        ///{Path} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_002 {
            get {
                return ResourceManager.GetString("MSG-002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   商品情報の読み込みに失敗しました。
        ///システム管理者へ連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_003 {
            get {
                return ResourceManager.GetString("MSG-003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫一覧情報の読み込みに失敗しました。
        ///ファイル[inventory.csv]が見つかりません。
        ///以下の場所にファイルが保存されているか確認してください。
        ///{Path} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_004 {
            get {
                return ResourceManager.GetString("MSG-004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫一覧情報の読み込みに失敗しました。
        ///ファイル[inventory.csv]が破損しています。
        ///ファイルの内容が正しいか確認してください。
        ///{Path} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_005 {
            get {
                return ResourceManager.GetString("MSG-005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫一覧情報の読み込みに失敗しました。
        ///システム管理者へ連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_006 {
            get {
                return ResourceManager.GetString("MSG-006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売実績情報の読み込みに失敗しました。
        ///ファイル[sales_yyyyMMdd.csv]が見つかりません。
        ///以下の場所にファイルが保存されているか確認してください。
        ///{Path} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_007 {
            get {
                return ResourceManager.GetString("MSG-007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売実績情報の読み込みに失敗しました。
        ///ファイル[sales_yyyyMMdd.csv]が破損しています。
        ///ファイルの内容が正しいか確認してください。
        ///{Path} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_008 {
            get {
                return ResourceManager.GetString("MSG-008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   販売実績情報の読み込みに失敗しました。
        ///システム管理者へ連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_009 {
            get {
                return ResourceManager.GetString("MSG-009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   データの集計に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_010 {
            get {
                return ResourceManager.GetString("MSG-010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   集計一覧の出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_011 {
            get {
                return ResourceManager.GetString("MSG-011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   詳細表示に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_012 {
            get {
                return ResourceManager.GetString("MSG-012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   該当するデータが見つかりません。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_013 {
            get {
                return ResourceManager.GetString("MSG-013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   売上販売実績一覧の出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_014 {
            get {
                return ResourceManager.GetString("MSG-014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫一覧の取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_015 {
            get {
                return ResourceManager.GetString("MSG-015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   在庫一覧の出力に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_016 {
            get {
                return ResourceManager.GetString("MSG-016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗/商品/区分マスタの取得に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_017 {
            get {
                return ResourceManager.GetString("MSG-017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   店舗名/商品名/区分名が重複しています。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_018 {
            get {
                return ResourceManager.GetString("MSG-018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   マスタの保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_019 {
            get {
                return ResourceManager.GetString("MSG-019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定情報の取得に失敗しました。
        ///システム管理者へ連絡してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_020 {
            get {
                return ResourceManager.GetString("MSG-020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   設定の保存に失敗しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_021 {
            get {
                return ResourceManager.GetString("MSG-021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   区分マスタデータがありません。
        ///区分登録から行ってください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MSG_022 {
            get {
                return ResourceManager.GetString("MSG-022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   これはテストです。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
    }
}
